Azure CI: retry installing nix on Linux
Works around https://github.com/NixOS/nix/issues/2805

diff --git a/.azure/azure-nightly-template-linux.yml b/.azure/azure-nightly-template-linux.yml
--- a/.azure/azure-nightly-template-linux.yml
+++ b/.azure/azure-nightly-template-linux.yml
@@ -28,7 +28,12 @@ jobs:
       AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
     displayName: 'Installation ${{parameters.os}}'
   - script: |
-      curl https://nixos.org/nix/install | sh
+      # Retry installing nix due to nondeterministic error
+      #   Fatal error: glibc detected an invalid stdio handle
+      # See:
+      #   https://github.com/nh2/static-haskell-nix/pull/27#issuecomment-502652181
+      #   https://github.com/NixOS/nix/issues/2733
+      (for i in {1..5}; do bash <(curl https://nixos.org/nix/install) && exit 0; done; exit 1)
       source ~/.profile
       export STACK_ROOT="$(Build.SourcesDirectory)"/.stack-root;
       export PATH=$HOME/.local/bin:$PATH;
